const host = 'http://127.0.0.1:5000/api/v1';
export const registerUrl     = host + '/register';
export const loginUrl        = host + '/login';
export const newTopicUrl     = host + '/topic';
export const updateTopicUrl  = host + '/topic';
export const starTopicUrl    = host + '/star';
export const voteTopicUrl    = host + '/topic/vote';
export const hotUrl          = host + '/hot';
export const taViewUrl       = host + '/topic/detail';
